version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # Define a rede que este serviço usará
    networks:
      - crm_network
    # Garante que a aplicação só inicie depois que os outros serviços estiverem prontos
    depends_on:
      - db
      - redis
    command: sleep infinity

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    # Define a rede que este serviço usará
    networks:
      - crm_network

  redis:
    image: redis:latest
    restart: unless-stopped
    # Define a rede que este serviço usará
    networks:
      - crm_network

volumes:
  mariadb-data:

# Define a nossa rede customizada
networks:
  crm_network:
    driver: bridge
